version: "3.9"
services:

  rpi-fan-control:
    build: ./
    image: rpi-fan-control:v1.3
    container_name: rpi-fan-control
    environment:
      - GPIO_PIN=21
      - POLL_INTERVAL=5
      - TEMP_FAN_ON=55
      - TEMP_FAN_OFF=50
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    networks:
      - fancontrol-network
    restart: always

networks:
  fancontrol-network:
    name: fancontrol-network
    driver: bridge
